esphome:
  platformio_options:
    build_flags:
      - "-DCONFIG_COMPILER_OPTIMIZATION_PERF=y"
    board_build.arduino.memory_type: qio_opi

esp32:
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_PERF: "y"
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: "y"

psram:
  speed: 80MHz

# --- API status ---
api:
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.show: lbl_hastatus
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.hide: lbl_hastatus

# --- Time ---
time:
  - platform: homeassistant
    id: ha_time

# --- Sensors ---
sensor:
  - platform: homeassistant
    id: weather_temp
    entity_id: weather.openweather
    attribute: temperature
  - platform: homeassistant
    id: weather_humidity
    entity_id: weather.openweather
    attribute: humidity
  - platform: homeassistant
    id: weather_dew_point
    entity_id: sensor.openweather_dew_point

text_sensor:
  - platform: homeassistant
    id: weather_condition
    entity_id: weather.openweather

# --- Fonts ---
font:
  - file: "gfonts://Montserrat"
    id: icon_font_14
    size: 14
    bpp: 4
    glyphs: ' !"%()+,-./0123456789:;?°·—ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzĄĆĘŁŃÓŚŹŻąćęłńóśźżµ³'
    extras:
      - file:
          type: web
          url: "https://github.com/Templarian/MaterialDesign-Webfont/raw/master/fonts/materialdesignicons-webfont.ttf"
        glyphs:
          - "\U000F0590"  # weather-cloudy
          - "\U000F0591"  # weather-fog
          - "\U000F0592"  # weather-hail
          - "\U000F0593"  # weather-lightning
          - "\U000F0594"  # weather-night
          - "\U000F0595"  # weather-partly-cloudy
          - "\U000F0596"  # weather-pouring
          - "\U000F0597"  # weather-rainy
          - "\U000F0598"  # weather-snowy
          - "\U000F0599"  # weather-sunny
          - "\U000F059D"  # weather-windy
          - "\U000F059E"  # weather-windy-variant
          - "\U000F067E"  # weather-lightning-rainy
          - "\U000F067F"  # weather-snowy-rainy
          - "\U000F058E"  # water-percent
          - "\U000F050F"  # thermometer
          - "\U000F07D0"  # home-assistant
  - file: "gfonts://Montserrat"
    id: icon_font_28
    size: 28
    bpp: 4
    glyphs: " "
    extras:
      - file:
          type: web
          url: "https://github.com/Templarian/MaterialDesign-Webfont/raw/master/fonts/materialdesignicons-webfont.ttf"
        glyphs:
          - "\U000F0590"  # weather-cloudy
          - "\U000F0591"  # weather-fog
          - "\U000F0592"  # weather-hail
          - "\U000F0593"  # weather-lightning
          - "\U000F0594"  # weather-night
          - "\U000F0595"  # weather-partly-cloudy
          - "\U000F0596"  # weather-pouring
          - "\U000F0597"  # weather-rainy
          - "\U000F0598"  # weather-snowy
          - "\U000F0599"  # weather-sunny
          - "\U000F059D"  # weather-windy
          - "\U000F059E"  # weather-windy-variant
          - "\U000F067E"  # weather-lightning-rainy
          - "\U000F067F"  # weather-snowy-rainy
  - file: "gfonts://Montserrat"
    id: font_18
    size: 18
    bpp: 4
    glyphs: ' !"%()+,-./0123456789:;?°·—ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzĄĆĘŁŃÓŚŹŻąćęłńóśźżµ³'

# --- LVGL UI ---
lvgl:
  theme:
    label:
      text_font: icon_font_14
      text_color: 0xFFFFFF
    button:
      bg_color: 0x2A2A3E
      bg_opa: COVER
      border_width: 0
      radius: 12
      text_color: 0xFFFFFF
      pressed:
        bg_color: 0x3A3A4E
      checked:
        bg_color: 0xE8A030
        text_color: 0x1A1A2E
    buttonmatrix:
      bg_opa: TRANSP
      border_width: 0
      text_color: 0xFFFFFF
      pad_all: 4
      items:
        bg_color: 0x2A2A3E
        bg_opa: COVER
        border_width: 0
        radius: 8
        text_color: 0xFFFFFF
        pressed:
          bg_color: 0x3A3A4E
        checked:
          bg_color: 0xE8A030
          text_color: 0x1A1A2E
    switch:
      bg_color: 0x404050
      bg_opa: COVER
      checked:
        bg_color: 0xE8A030
        bg_opa: COVER
      knob:
        bg_color: 0xFFFFFF
        bg_opa: COVER
    slider:
      bg_color: 0x303040
      bg_opa: COVER
      border_width: 0
      indicator:
        bg_color: 0xE8A030
        bg_opa: COVER
      knob:
        bg_color: 0xFFFFFF
        bg_opa: COVER
        border_width: 0
  style_definitions:
    - id: card
      bg_color: 0x1C1C2E
      bg_opa: COVER
      border_width: 0
      radius: 12
      pad_all: 12
      text_color: 0xFFFFFF
    - id: chip
      bg_color: 0x2A2A3E
      bg_opa: COVER
      border_width: 0
      radius: 16
      pad_left: 12
      pad_right: 12
      pad_top: 4
      pad_bottom: 4
      text_color: 0xFFFFFF
    - id: section_title
      text_color: 0x9E9E9E
      bg_opa: TRANSP
  pages:
    - id: main_page
      bg_color: 0x000000
      scrollbar_mode: "OFF"
      scrollable: false
      widgets:
        # Status bar
        - obj:
            width: 800
            height: 32
            border_width: 0
            radius: 0
            scrollbar_mode: "OFF"
            scrollable: false
            x: 0
            y: 0
            bg_color: 0x1A1A1A
            bg_opa: COVER
            pad_left: 8
            pad_right: 8
            widgets:
              - label:
                  id: lbl_clock
                  align: LEFT_MID
                  text_color: 0xFFFFFF
                  text_font: montserrat_28
                  text: "--:--"
              - label:
                  id: lbl_weather_icon
                  align: LEFT_MID
                  x: 130
                  text_color: 0xFFFFFF
                  text_font: icon_font_28
                  text: ""
              - label:
                  id: lbl_weather_text
                  align: LEFT_MID
                  x: 164
                  text_color: 0xFFFFFF
                  text_font: icon_font_14
                  text: ""
              - label:
                  id: lbl_date
                  align: RIGHT_MID
                  x: -20
                  text_color: 0xFFFFFF
                  text_font: icon_font_14
                  text: ""
              - label:
                  id: lbl_hastatus
                  align: RIGHT_MID
                  hidden: true
                  text_color: 0xFFFFFF
                  text_font: icon_font_14
                  text: "\U000F07D0"
        # --- Column 1: Strefa dzienna ---
        - obj:
            styles: card
            x: 8
            y: 40
            width: 256
            height: 432
            scrollable: false
            widgets:
              - label:
                  text: "Strefa dzienna"
                  text_font: font_18
              - label:
                  y: 28
                  text: "21,1 °C"
                  text_font: montserrat_28
              - label:
                  y: 60
                  text_color: 0x9E9E9E
                  text: "48,0%  ·  p.rosy 9,7 °C"
              - label:
                  y: 88
                  text_color: 0x9E9E9E
                  text: "Grzejnik: 21,5 °C"
              - label:
                  y: 108
                  text_color: 0x9E9E9E
                  text: "Okno: zamknięte"
              # Lights
              - obj:
                  y: 140
                  width: 232
                  height: 36
                  bg_color: 0x2A2A3E
                  bg_opa: COVER
                  radius: 8
                  border_width: 0
                  scrollable: false
                  widgets:
                    - label:
                        align: LEFT_MID
                        x: 8
                        text: "Salon Góra"
                    - label:
                        align: RIGHT_MID
                        x: -8
                        text: "Off"
                        text_color: 0x9E9E9E
              - obj:
                  y: 182
                  width: 232
                  height: 36
                  bg_color: 0x2A2A3E
                  bg_opa: COVER
                  radius: 8
                  border_width: 0
                  scrollable: false
                  widgets:
                    - label:
                        align: LEFT_MID
                        x: 8
                        text: "Kuchnia Góra"
                    - label:
                        align: RIGHT_MID
                        x: -8
                        text: "54%"
                        text_color: 0xE8A030
              - obj:
                  y: 224
                  width: 232
                  height: 36
                  bg_color: 0x2A2A3E
                  bg_opa: COVER
                  radius: 8
                  border_width: 0
                  scrollable: false
                  widgets:
                    - label:
                        align: LEFT_MID
                        x: 8
                        text: "Przedpokój Góra"
                    - label:
                        align: RIGHT_MID
                        x: -8
                        text: "52%"
                        text_color: 0xE8A030
              # Devices
              - label:
                  y: 276
                  text_color: 0x9E9E9E
                  text: "Zmywarka: wyłączona"
              - label:
                  y: 296
                  text_color: 0x9E9E9E
                  text: "Mokradełko: 50%"
              - label:
                  y: 316
                  text_color: 0x9E9E9E
                  text: "Czyścidełko: auto"
              - label:
                  y: 336
                  text_color: 0x9E9E9E
                  text: "PM2.5: 22 µg/m³"
        # --- Column 2: Sypialnia ---
        - obj:
            styles: card
            x: 272
            y: 40
            width: 256
            height: 432
            scrollable: false
            widgets:
              - label:
                  text: "Sypialnia"
                  text_font: font_18
              - label:
                  y: 28
                  text: "18,5 °C"
                  text_font: montserrat_28
              - label:
                  y: 60
                  text_color: 0x9E9E9E
                  text: "42,9%  ·  p.rosy 5,6 °C"
              - label:
                  y: 88
                  text_color: 0x9E9E9E
                  text: "Grzejnik: 18,5 °C"
              - label:
                  y: 108
                  text_color: 0x9E9E9E
                  text: "Okna: zamknięte"
              # Lights
              - obj:
                  y: 140
                  width: 232
                  height: 36
                  bg_color: 0x2A2A3E
                  bg_opa: COVER
                  radius: 8
                  border_width: 0
                  scrollable: false
                  widgets:
                    - label:
                        align: LEFT_MID
                        x: 8
                        text: "Sypialnia Góra"
                    - label:
                        align: RIGHT_MID
                        x: -8
                        text: "Off"
                        text_color: 0x9E9E9E
              - obj:
                  y: 182
                  width: 232
                  height: 36
                  bg_color: 0x2A2A3E
                  bg_opa: COVER
                  radius: 8
                  border_width: 0
                  scrollable: false
                  widgets:
                    - label:
                        align: LEFT_MID
                        x: 8
                        text: "Lampa Stojąca"
                    - label:
                        align: RIGHT_MID
                        x: -8
                        text: "10%"
                        text_color: 0xE8A030
              # Devices
              - label:
                  y: 234
                  text_color: 0x9E9E9E
                  text: "TV: Off"
        # --- Column 3: Łazienka ---
        - obj:
            styles: card
            x: 536
            y: 40
            width: 256
            height: 432
            scrollable: false
            widgets:
              - label:
                  text: "Łazienka"
                  text_font: font_18
              # Light
              - obj:
                  y: 32
                  width: 232
                  height: 36
                  bg_color: 0x2A2A3E
                  bg_opa: COVER
                  radius: 8
                  border_width: 0
                  scrollable: false
                  widgets:
                    - label:
                        align: LEFT_MID
                        x: 8
                        text: "Łazienka"
                    - label:
                        align: RIGHT_MID
                        x: -8
                        text: "Off"
                        text_color: 0x9E9E9E
              # Devices
              - label:
                  y: 84
                  text_color: 0x9E9E9E
                  text: "Pralka: —"
              - label:
                  y: 104
                  text_color: 0x9E9E9E
                  text: "Suszarka: —"

# --- Clock update ---
interval:
  - interval: 1s
    then:
      - lvgl.label.update:
          id: lbl_clock
          text: !lambda |-
            auto now = id(ha_time).now();
            if (!now.is_valid()) return std::string("--:--");
            char buf[6];
            snprintf(buf, sizeof(buf), "%02d:%02d", now.hour, now.minute);
            return std::string(buf);
      - lvgl.label.update:
          id: lbl_weather_icon
          text: !lambda |-
            auto cond = id(weather_condition).state;
            if (cond.empty()) return std::string("");
            if (cond == "cloudy") return std::string("\U000F0590");
            if (cond == "clear-night") return std::string("\U000F0594");
            if (cond == "fog") return std::string("\U000F0591");
            if (cond == "hail") return std::string("\U000F0592");
            if (cond == "lightning") return std::string("\U000F0593");
            if (cond == "lightning-rainy") return std::string("\U000F067E");
            if (cond == "partlycloudy") return std::string("\U000F0595");
            if (cond == "pouring") return std::string("\U000F0596");
            if (cond == "rainy") return std::string("\U000F0597");
            if (cond == "snowy") return std::string("\U000F0598");
            if (cond == "snowy-rainy") return std::string("\U000F067F");
            if (cond == "sunny") return std::string("\U000F0599");
            if (cond == "windy") return std::string("\U000F059D");
            if (cond == "windy-variant") return std::string("\U000F059E");
            return std::string("\U000F0590");
      - lvgl.label.update:
          id: lbl_weather_text
          text: !lambda |-
            auto cond = id(weather_condition).state;
            float temp = id(weather_temp).state;
            float hum = id(weather_humidity).state;
            float dew = id(weather_dew_point).state;
            if (cond.empty() || std::isnan(temp)) return std::string("");
            std::string desc;
            if (cond == "cloudy") desc = "pochmurno";
            else if (cond == "clear-night") desc = "bezchmurnie";
            else if (cond == "fog") desc = "mg\u0142a";
            else if (cond == "hail") desc = "grad";
            else if (cond == "lightning") desc = "burza";
            else if (cond == "lightning-rainy") desc = "burza";
            else if (cond == "partlycloudy") desc = "cz. zachmurzenie";
            else if (cond == "pouring") desc = "ulewa";
            else if (cond == "rainy") desc = "deszcz";
            else if (cond == "snowy") desc = "snieg";
            else if (cond == "snowy-rainy") desc = "snieg z deszcz.";
            else if (cond == "sunny") desc = "slonecznie";
            else if (cond == "windy") desc = "wietrznie";
            else if (cond == "windy-variant") desc = "wietrznie";
            else desc = cond;
            char buf[80];
            snprintf(buf, sizeof(buf), "%.0f°C  %s", temp, desc.c_str());
            std::string result = buf;
            if (!std::isnan(hum)) {
              snprintf(buf, sizeof(buf), "   \U000F058E %.0f%%", hum);
              result += buf;
            }
            if (!std::isnan(dew)) {
              snprintf(buf, sizeof(buf), "   \U000F050F %.0f°C", dew);
              result += buf;
            }
            return result;
      - lvgl.label.update:
          id: lbl_date
          text: !lambda |-
            auto now = id(ha_time).now();
            if (!now.is_valid()) return std::string("");
            const char *days[] = {"niedz.", "pon.", "wt.", "śr.", "czw.", "pt.", "sob."};
            const char *months[] = {"stycznia", "lutego", "marca", "kwietnia", "maja", "czerwca",
                                    "lipca", "sierpnia", "września", "października", "listopada", "grudnia"};
            char buf[40];
            snprintf(buf, sizeof(buf), "%s, %d %s %d r.", days[now.day_of_week - 1], now.day_of_month, months[now.month - 1], now.year);
            return std::string(buf);
