esphome:
  platformio_options:
    build_flags:
      - "-DCONFIG_COMPILER_OPTIMIZATION_PERF=y"
    board_build.arduino.memory_type: qio_opi

esp32:
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_PERF: "y"
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: "y"

psram:
  speed: 80MHz

# --- Sensors ---
sensor:

# --- LVGL UI ---
lvgl:
